sudo: required
langauge: generic
services:
  - docker

before_install:
  - docker build -t vivekchole/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vivekchole/docker-react npm run test
  